name: Build Desktop App

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies (shared)
        working-directory: ./keenfresh-shared
        run: npm ci

      - name: Build shared library
        working-directory: ./keenfresh-shared
        run: npm run build

      - name: Install dependencies (desktop)
        working-directory: ./keenfresh-desktop
        run: npm ci



      - name: Build and Publish Windows App
        if: matrix.os == 'windows-latest'
        working-directory: ./keenfresh-desktop
        run: npm run release:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Mac App
        if: matrix.os == 'macos-13'
        working-directory: ./keenfresh-desktop
        run: npm run release:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Linux Build Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxtst-dev libpng-dev

      - name: Build and Publish Linux App
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./keenfresh-desktop
        run: npm run release:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
